### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tolomaus** [lejon/T-SNE-Java#12]
Hi Leif,

Could you tell me under what license your code exists?

I would like to use it for a commercial project but only internally.

Thanks in advance

**Comment by lejon** [comment]
Hi,

It's a 3-clause BSD license so commercial use is allowed. 

https://github.com/lejon/T-SNE-Java/blob/master/tsne-core/LICENSE.md

Best regards,
-Leif

**Comment by tolomaus** [comment]
Cool thanks for making your work publicly available, much appreciated!
