### ISSUE TITLE
Release 2.4.0 contains 2.3.0 jar

### ISSUE THREAD

**Issue by gyscos** [lejon/T-SNE-Java#13]
Release [2.4.0](https://github.com/lejon/T-SNE-Java/releases/tag/v2.4.0) contains the [tsne-2.3.0.jar](https://github.com/lejon/T-SNE-Java/releases/download/v2.4.0/tsne-2.3.0.jar) file, is it actually the up-to-date one?

**Comment by lejon** [comment]
Yes, i realise it is a bit confusing...
So the tsne-core is version 2.3.0 while tsne-demos is version 2.4.0.
So it is correct...
