### ISSUE TITLE
Barnes hut example in the readme

### ISSUE THREAD

**Issue by odinsbane** [lejon/T-SNE-Java#15]
The example in the readme references a method that doesn't exist.

    double [][] Y = tsne.tsne(X, 2, initial_dims, perplexity); 

I replaced it with:

    TSneConfig config = new TSneConfig(X, 2, initial_dims, perplexity, 1000000, true, 0.5, true, true);
    double [][] Y = tsne.tsne(config);   
    
That seems to work, as I get some result.

**Comment by lejon** [comment]
Thanks! Corrected!
