### ISSUE TITLE
ImageJ port of T-SNE-Java

### ISSUE THREAD

**Issue by antinos** [lejon/T-SNE-Java#19]
Hi Leif,
In the last week I have created an ImageJ port (https://github.com/antinos/T-SNE-ImageJ) of your t-SNE java implementation. I'm not a programmer by profession and haven't got much experience with Github repos. I didn't fork your project but instead downloaded it to add to my build. I also needed to change the ejml folder structure to avoid .jar conflicts in ImageJ. I hope I didn't break Github etiquette. I have referenced you in the Readme file, the project brief description, and in my dialogues on the ImageJ forum. I have also added your repo info as comments in the source.
Please let me know if you would prefer me to handle the use and/or the distribution of your source in another manner.

Kind regards.

**Comment by lejon** [comment]
Hi, 

I'm not sure what ImageJ / Fiji does, but if it is only the GUI parts I guess you should be able to use the T-Sne core as a library. 
Anyways, that's what's so great with open source, can do whatever you want with it! :) 

Cheers!
