### ISSUE TITLE
The project does not build after checkouts

### ISSUE THREAD

**Issue by glennbech** [lejon/T-SNE-Java#2]
due to  dependencies to de.berlios.jmathtools artifacts.

**Comment by lejon** [comment]
Hmm, sorry for the late reply to this, I didn't seem to get notified about comments, some GitHub setting I guess.

I built it cleanly today (2015-03-06) and it worked. Are you building with Maven or in an IDE or by some other means?

If you are using Maven, it should find and download the berlios artefacts.

**Comment by sebastian-alfers** [comment]
i use "$ mvn package" and also get errors

[ERROR] Failed to execute goal on project tsne: Could not resolve dependencies for project com.jujutsu.tsne:tsne:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: de.berlios.jmathtools:jmathio:jar:1.0.0, de.berlios.jmathtools:jmatharray:jar:1.0.0, de.berlios.jmathtools:jmathplot:jar:1.0.0: Failure to find de.berlios.jmathtools:jmathio:jar:1.0.0 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by lejon** [comment]
Hi, sorry it has taken so long time to respond to this, I have now refactored the code so only the demo part depends on berlios. You should now be able to build tsne in itself, but I still have to fix the demos part. I guess it will require downloading the berlios jars. Unless I can distribute them here. Will have a look into that...

**Comment by glennbech** [comment]
Excellent, clean/install works now, however the unit tests has errors :-)
Thanks for the refactoring, I will look into the code. I have another
projet where I try to port a Javascript version to Java myself while
learning the needed statistics terms as I go :)

**Comment by lejon** [comment]
Thanks for the feedback! Oops, I need a CI machine! :) Better have a look at that. Have been doing a lot of refactoring in the demos part also. It builds for me now, but I only have two machines to test on currently so I don't guarantee a clean build for the demos unfortunately.
