### ISSUE TITLE
Maven Hosting

### ISSUE THREAD

**Issue by sameersingh** [lejon/T-SNE-Java#4]
Is this project hosted on any public maven repositories?

Making it an easy dependency to include in current Maven projects will really help adoption. Of course, Maven Central is the easiest for users, but any public repo would be great.

**Comment by lejon** [comment]
Sorry it is not at the moment, I haven't really had time to investigate how that stuff works, but I have been thinking about it, so perhaps it will happen. :)

**Comment by lejon** [comment]
Thanks! Maven Central is just too complicated to get going with for me right now. You can get the corresponding functionality by using Jitpack:

<repositories>
<repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
</repository>
</repositories>

<dependency>
    <groupId>com.github.User</groupId>
    <artifactId>Repo</artifactId>
    <version>Tag</version>
</dependency>

**Comment by froshyfrosh** [comment]
To make life a bit easier for others:
User: lejon
Repo: T-SNE-Java
Version: v2.5.0
(Note: the version tag starts with a "v")
For Gradle: 
repositories {
    ...
    maven {
        url 'https://jitpack.io'
    }
}
dependencies {
    ...
    compile 'com.github.lejon:T-SNE-Java:v2.5.0'
}

**Comment by javagl** [comment]
I hope it is OK to mention this here: 

I have derived a "lean" version from T-SNE-Java that just contains the minimal code+dependencies for the Barnes-Hut-t-SNE. It is available at https://github.com/javagl/bh-tsne and in Maven Central as
```
<dependency>
    <groupId>de.javagl</groupId>
    <artifactId>bh-tsne</artifactId>
    <version>0.0.1</version>
</dependency>
```

All credits to the original implementors.

**Comment by lejon** [comment]
👍
