### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by mvaudel** [lejon/T-SNE-Java#6]
Hi Leif,

Is it possible to pass labels of the different lines and get them in the output? Can we assume that the order is conserved?

Thanks for your help!

Marc

**Comment by lejon** [comment]
Yes if you are running the TSneCsv version there is a “label_file” argument that can be used to supply the labels. 
And Yes, the ordering is preserved.

Cheers!
-Leif

**Comment by mvaudel** [comment]
Great, thanks! Really enjoying your library, thanks for it!

**Comment by lejon** [comment]
Thanks for the kind words! :)

I have now done some, long needed, updates to the README and a version 1.0 release. So hopefully it is a bit better!

Cheers!
-Leif
