### ISSUE TITLE
Missing resources for tests

### ISSUE THREAD

**Issue by poseidon42** [lejon/T-SNE-Java#7]
Hi,
I ran into test-failures for t-sne because of missing resources src/main/python/[...].txt that are referenced in /tsne/src/test/java/com/jujutsu/tsne/EJMLVsPython.java and /tsne/src/test/java/com/jujutsu/tsne/MatrixOpVsPython.java, but they are not under version-control.
Maybe you could include all needen resources in GitHub?
Kind Regards
Poseidon

**Comment by lejon** [comment]
Hmm, that is strange since the Travis build passes, it only uses the GitHub repo...
I'll have a look when I get some time over, I'm extremely busy right now unfortunately...

**Comment by lejon** [comment]
Fixed with commit 029d087.
